# Generated by Django 4.2 on 2023-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_time_added_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
